config/routes.rb
Rails.application.routes.draw do
  root to: "items#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  
  
  resources :users, only: [:index, :show]
  resources :items
  resources :purchases, only:[:index, :create]
  get '/items/:id', to: 'items#index', as: :index_item
  get '/items/:id', to: 'items#show', as: :show_item
  patch '/items/:id', to: 'items#update', as: :update_item
  delete '/items/:id', to: 'items#destroy', as: :destroy_item
  get '/purchases/:id', to: 'purchases#index', as: :index_purchase
  post '/purchases/:id', to: 'purchases#create', as: :create_purchase
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  before_action :user_restriction, only: [:index]
  before_action :set_item, only: [:create]
  def index 
    @user = current_user
    @purchase = Purchase.new
    @item = Item.find(params[:id])
    @address = Address.new
  end

  def create
    @purchase = Purchase.new
    @purchase.user = current_user
    @purchase.item = @item
    @address = Address.new(address_params)
    @address.item = @item
    @user = User.find(params[:id])
    if @purchase.save && @address.save
      pay_item
      return redirect_to root_path
    else
      render :index
    end
  end
  
  private

  def address_params
    params.require(:purchase).permit(:postal, :japan_id, :city, :town, :building, :phone_number)
  end

  def set_item
    @item = Item.find(params[:format])
  end


  def pay_item
    @item = Item.find(params[:format])
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]           # PAY.JPテスト秘密鍵
    Payjp::Charge.create(
      amount: @item.price,
      card: params['token'],    # カードトークン
      currency:'jpy'                 # 通貨の種類
    )
  end

  def user_restriction
    if current_user == @user 
      redirect_to root_path
    end
  end

end
  

app/views/purchases/index.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      購入内容の確認
    </h1>
    <%# 購入内容の表示 %>
      <div class='buy-item-info'>
        <%= image_tag @item.image, class: 'buy-item-img' %>
        <div class='buy-item-right-content'>
          <h2 class='buy-item-text'>
            <%= @item.explain %>
          </h2>
          <div class='buy-item-price'>
            <p class='item-price-text'>¥<%= @item.price %></p>
            <p class='item-price-sub-text'>（税込）送料込み</p>
          </div>
        </div>
      </div>
      <%# /購入内容の表示 %>
      <% if @address.errors.any? %>
        <div class="error-alert">
          <ul>
            <% @address.errors.full_messages.each do |message| %>
              <li class='error-message'><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%# 支払額の表示 %>
      <div class='item-payment'>
        <h1 class='item-payment-title'>
          支払金額
        </h1>
        <p class='item-payment-price'>
          ¥<%= @item.price %>
        </p>
      </div>
    <%# /支払額の表示 %>
  
    <%= form_with model: @purchase, url: create_purchase_path(@user.id, @item.id), method: "post", id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
      <%# カード情報の入力 %>
     
      <div class='credit-card-form'>
        <h1 class='info-input-haedline'>
          クレジットカード情報入力
        </h1>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">カード情報</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :name, class:"input-default", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
          <div class='available-card'>
            <%= image_tag 'card-visa.gif', class: 'card-logo'%>
            <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
            <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
            <%= image_tag 'card-amex.gif', class: 'card-logo'%>
          </div>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">有効期限</label>
            <span class="indispensable">必須</span>
          </div>
          <div class='input-expiration-date-wrap'>
            <%= f.text_area :purchase_exp_month, class:"input-expiration-date", placeholder:"例)3" %>
            <p>月</p>
            <%= f.text_area :purchase_exp_year, class:"input-expiration-date", placeholder:"例)23" %>
            <p>年</p>
          </div>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">セキュリティコード</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :purchase_cvc, class:"input-default", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
        </div>
      </div>
      <%# /カード情報の入力 %>
      <%# 配送先の入力 %>
      <div class='shipping-address-form'>
        <h1 class='info-input-haedline'>
          配送先入力
        </h1>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">郵便番号</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :postal , class:"input-default", placeholder:"例）123-4567", maxlength:"8" %>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">都道府県</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:japan_id, Japan.all, :id, :name, {include_blank:"---"}, {class:"select-box"}) %>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">市区町村</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :city, class:"input-default", placeholder:"例）横浜市緑区"%>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">番地</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :town, class:"input-default", placeholder:"例）青山1-1-1"%>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">建物名</label>
            <span class="form-any">任意</span>
          </div>
          <%= f.text_field :building, class:"input-default", placeholder:"例）柳ビル103"%>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">電話番号</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :phone_number, class:"input-default", placeholder:"例）09012345678",maxlength:"11"%>
        </div>
      </div>
      <div class='buy-btn'>
        <%= f.submit "購入", class:"buy-red-btn" %>
      </div>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>

app/views/purchases/user.html.erb
<%= render "shared/second-header" %> 

<%= form_with class:'registration-main',local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      会員情報入力
    </h1>
  </div>

  <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
  <%# render 'shared/error_messages', model: f.object %>
  <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :nickname, class:"input-default", placeholder:"例) furima太郎", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password, class:"input-default", placeholder:"6文字以上の半角英数字" %>
    <p class='info-text'>※英字と数字の両方を含めて設定してください</p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード(確認)</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password_confirmation, class:"input-default", placeholder:"同じパスワードを入力して下さい" %>
  </div>
  <div class="form-group">
    <p class='form-info-header'>
      本人確認
    </p>
    <p class='form-info-text'>
      安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
    </p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :h_last_name, class:"input-name", placeholder:"例) 山田" %>
      <%= f.text_area :h_first_name, class:"input-name", placeholder:"例) 陸太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :k_last_name, class:"input-name", placeholder:"例) ヤマダ" %>
      <%= f.text_area :k_first_name, class:"input-name", placeholder:"例) リクタロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <p class='info-text'>※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。</p>
  </div>
  <div class="form-group">
    <h2 class='form-bottom-text'>
      「会員登録」のボタンを押すことにより、
      <span>利用規約</span>
      <br>に同意したものとみなします
    </h2>
  </div>
  <div class='register-btn'>
    <%= f.submit "会員登録" ,class:"register-red-btn" %>
    
  </div>
  <p class='register-info'>本人情報の登録について</p>
</div>
<% end %>

<%= render "shared/second-footer"%>